// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantManagementSystem.Data;

#nullable disable

namespace RestaurantManagementSystem.Migrations
{
    [DbContext(typeof(RestaurantManagementSystemContext))]
    [Migration("20241011103320_UpdatedSeededInformationYetAgain")]
    partial class UpdatedSeededInformationYetAgain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestaurantManagementSystem.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReservationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("RestaurantManagementSystem.Models.BookingTable", b =>
                {
                    b.Property<int>("BookingTableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingTableId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReservationEndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReservationStartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.HasKey("BookingTableId");

                    b.HasIndex("BookingId");

                    b.HasIndex("TableId");

                    b.ToTable("BookingTables");
                });

            modelBuilder.Entity("RestaurantManagementSystem.Models.Dish", b =>
                {
                    b.Property<int>("DishId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DishId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DishName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int?>("MenuId")
                        .HasColumnType("int");

                    b.Property<bool>("Popular")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("DishId");

                    b.HasIndex("MenuId");

                    b.ToTable("Dishes");

                    b.HasData(
                        new
                        {
                            DishId = 1,
                            Description = "A refined take on the classic Caprese, with creamy mozzarella, ripe heirloom tomatoes, and a drizzle of fragrant basil pesto.",
                            DishName = "Caprese D'Oro",
                            IsAvailable = true,
                            MenuId = 1,
                            Popular = false,
                            Price = 28.00m
                        },
                        new
                        {
                            DishId = 2,
                            Description = "A delicate seabass carpaccio served over crisp red cabbage slaw, garnished with pink peppercorns and a drizzle of citrus olive oil.",
                            DishName = "Carpaccio di Branzino",
                            IsAvailable = true,
                            MenuId = 1,
                            Popular = false,
                            Price = 42.00m
                        },
                        new
                        {
                            DishId = 3,
                            Description = "A symphony of grilled vegetables, including zucchini, eggplant, and roasted peppers, drizzled with a delicate balsamic reduction.",
                            DishName = "Verdure alla Griglia",
                            IsAvailable = true,
                            MenuId = 1,
                            Popular = false,
                            Price = 28.00m
                        },
                        new
                        {
                            DishId = 4,
                            Description = "Freshly made tagliolini pasta wrapped in a delicate creamy sauce, topped with succulent shrimp marinated in herbs and citrus.",
                            DishName = "Tagliolini Primavera",
                            IsAvailable = true,
                            MenuId = 2,
                            Popular = true,
                            Price = 38.00m
                        },
                        new
                        {
                            DishId = 5,
                            Description = "Soft, pillowy gnocchi paired with a fragrant seafood medley of clams, infused with garlic, white wine, and a touch of lemon.",
                            DishName = "Gnocchi di Mare",
                            IsAvailable = true,
                            MenuId = 2,
                            Popular = true,
                            Price = 45.00m
                        },
                        new
                        {
                            DishId = 6,
                            Description = "A vibrant dish of fresh pasta mingling with sweet cherry tomatoes, tender tuna, and zesty oranges.",
                            DishName = "Pasta Tricolore",
                            IsAvailable = true,
                            MenuId = 2,
                            Popular = true,
                            Price = 42.00m
                        },
                        new
                        {
                            DishId = 7,
                            Description = "A lavish platter of lightly battered and fried seafood, featuring crispy prawns, calamari, and anchovies.",
                            DishName = "Fritto Misto",
                            IsAvailable = true,
                            MenuId = 2,
                            Popular = false,
                            Price = 48.00m
                        },
                        new
                        {
                            DishId = 8,
                            Description = "A trio of hand-cut raw delicacies featuring buttery salmon, tender tuna, and delicate seabass, served with citrus and avocado cream.",
                            DishName = "Tris di Crudo",
                            IsAvailable = true,
                            MenuId = 2,
                            Popular = true,
                            Price = 55.00m
                        },
                        new
                        {
                            DishId = 9,
                            Description = "Exquisitely seared tuna wrapped in a crispy golden crust, set on a bed of julienned vegetables, and paired with a balsamic reduction.",
                            DishName = "Tonno Dorato",
                            IsAvailable = true,
                            MenuId = 2,
                            Popular = true,
                            Price = 52.00m
                        },
                        new
                        {
                            DishId = 10,
                            Description = "A gourmet open-faced tart with house-smoked anchovies, fennel, sun-dried tomatoes, and a hint of citrus zest.",
                            DishName = "Alici Affumicate",
                            IsAvailable = true,
                            MenuId = 2,
                            Popular = false,
                            Price = 35.00m
                        },
                        new
                        {
                            DishId = 11,
                            Description = "Luxuriously creamy tagliolini pasta adorned with fragrant shaved black truffles, offering an intense depth of flavor.",
                            DishName = "Tagliolini al Tartufo",
                            IsAvailable = true,
                            MenuId = 2,
                            Popular = true,
                            Price = 65.00m
                        },
                        new
                        {
                            DishId = 12,
                            Description = "A succulent Florentine-style T-bone steak, grilled to perfection and served with crispy potato wedges.",
                            DishName = "Bistecca Fiorentina",
                            IsAvailable = true,
                            MenuId = 2,
                            Popular = false,
                            Price = 75.00m
                        },
                        new
                        {
                            DishId = 13,
                            Description = "Creamy Parmesan risotto topped with crispy kale and semi-dried tomatoes. A perfect blend of richness and texture that melts in your mouth.",
                            DishName = "Risotto al Parmigiano",
                            IsAvailable = true,
                            MenuId = 2,
                            Popular = false,
                            Price = 40.00m
                        },
                        new
                        {
                            DishId = 14,
                            Description = "Handcrafted paccheri pasta enveloped in a luscious tomato basil sauce, with a garnish of fresh basil leaves.",
                            DishName = "Paccheri al Pomodoro",
                            IsAvailable = true,
                            MenuId = 2,
                            Popular = false,
                            Price = 35.00m
                        },
                        new
                        {
                            DishId = 15,
                            Description = "Delicately sliced beef carpaccio topped with a golden-fried egg yolk and a hint of truffle mayo.",
                            DishName = "Carpaccio di Manzo",
                            IsAvailable = true,
                            MenuId = 2,
                            Popular = false,
                            Price = 58.00m
                        },
                        new
                        {
                            DishId = 16,
                            Description = "Perfectly seared cod fillet served with sautéed mushrooms and salty samphire, finished with a creamy white wine sauce.",
                            DishName = "Merluzzo con Funghi e Salicornia",
                            IsAvailable = true,
                            MenuId = 2,
                            Popular = false,
                            Price = 62.00m
                        },
                        new
                        {
                            DishId = 17,
                            Description = "Al dente rigatoni pasta tossed with savory Italian sausage and finished with crispy breadcrumbs and a sprinkle of chili threads.",
                            DishName = "Rigatoni con Salsiccia",
                            IsAvailable = true,
                            MenuId = 2,
                            Popular = false,
                            Price = 38.00m
                        },
                        new
                        {
                            DishId = 18,
                            Description = "Crisp corn tortillas filled with a refreshing mix of lightly marinated seafood, cucumber slices, and vine-ripened tomatoes.",
                            DishName = "Tacos di Mare",
                            IsAvailable = true,
                            MenuId = 3,
                            Popular = false,
                            Price = 36.00m
                        });
                });

            modelBuilder.Entity("RestaurantManagementSystem.Models.Menu", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuId"));

                    b.Property<string>("MenuName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MenuId");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            MenuId = 1,
                            MenuName = "Appetizer"
                        },
                        new
                        {
                            MenuId = 2,
                            MenuName = "Main Courses"
                        },
                        new
                        {
                            MenuId = 3,
                            MenuName = "Dessert"
                        });
                });

            modelBuilder.Entity("RestaurantManagementSystem.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Employee"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "Customer"
                        });
                });

            modelBuilder.Entity("RestaurantManagementSystem.Models.Table", b =>
                {
                    b.Property<int>("TableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TableId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.Property<int>("TableNumber")
                        .HasColumnType("int");

                    b.HasKey("TableId");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            TableId = 1,
                            Description = "A corner table by the large bay window, offering a stunning view of the city skyline. The soft glow of candlelight enhances the cozy yet sophisticated ambiance.",
                            Seats = 4,
                            TableNumber = 1
                        },
                        new
                        {
                            TableId = 2,
                            Description = "Intimate and secluded, this table is tucked away near a bookshelf wall adorned with vintage books. Perfect for a private dinner with soft, warm lighting.",
                            Seats = 2,
                            TableNumber = 2
                        },
                        new
                        {
                            TableId = 3,
                            Description = "A spacious table set beneath an elegant chandelier, surrounded by velvet curtains. Ideal for group gatherings, with a luxurious feel and a commanding view of the restaurant’s centerpiece fountain.",
                            Seats = 6,
                            TableNumber = 3
                        },
                        new
                        {
                            TableId = 4,
                            Description = "Nestled in a cozy alcove near the wine cellar, this table offers a secluded, intimate dining experience with a rich, aromatic ambiance and a view of the sommelier at work.",
                            Seats = 4,
                            TableNumber = 4
                        },
                        new
                        {
                            TableId = 5,
                            Description = "A window-side table with a direct view of the streetlights and evening passersby. Enveloped in soft leather chairs, it's perfect for a romantic dinner with a touch of urban charm.",
                            Seats = 2,
                            TableNumber = 5
                        },
                        new
                        {
                            TableId = 6,
                            Description = "Positioned at the heart of the restaurant, this grand table is ideal for celebrations. Surrounded by low-hanging pendant lights and lush greenery, it brings a touch of nature into the luxurious setting.",
                            Seats = 8,
                            TableNumber = 6
                        },
                        new
                        {
                            TableId = 7,
                            Description = "Located near the crackling fireplace, this table exudes warmth and coziness. The perfect setting for a family dinner, with the added comfort of soft armchairs and ambient lighting.",
                            Seats = 4,
                            TableNumber = 7
                        },
                        new
                        {
                            TableId = 8,
                            Description = "Situated on the elevated dining platform, offering a bird’s eye view of the entire restaurant. The dim lighting and plush seating make it ideal for larger groups seeking an exclusive experience.",
                            Seats = 6,
                            TableNumber = 8
                        },
                        new
                        {
                            TableId = 9,
                            Description = "A small, intimate table placed near the piano, where live music fills the air. With velvet upholstery and low lighting, it’s an unforgettable experience for music lovers.",
                            Seats = 2,
                            TableNumber = 9
                        },
                        new
                        {
                            TableId = 10,
                            Description = "This table offers a view of the chef’s open kitchen, allowing diners to watch the artistry unfold. Luxurious yet vibrant, it’s perfect for those who enjoy the theater of fine dining.",
                            Seats = 4,
                            TableNumber = 10
                        });
                });

            modelBuilder.Entity("RestaurantManagementSystem.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(380)
                        .HasColumnType("nvarchar(380)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "admin.istrator@thedot.com",
                            FirstName = "Admin",
                            LastName = "Istrator",
                            PasswordHash = "$2a$11$WPSTi5rsoQ4bygvCSGHIze9bztgI4QCvVfc7W.V7KgKu7gFmopQB6",
                            PhoneNumber = "+4670123456",
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            Email = "john.doe@thedot.com",
                            FirstName = "John",
                            LastName = "Doe",
                            PasswordHash = "$2a$11$4BxFB2IcLGWKxgBnVfWCtOG7OfxZ1DjCrbpOk98b.SSct39Vlg6.K",
                            PhoneNumber = "+4670123457",
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            Email = "jane.smith@thedot.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            PasswordHash = "$2a$11$4BxFB2IcLGWKxgBnVfWCtOG7OfxZ1DjCrbpOk98b.SSct39Vlg6.K",
                            PhoneNumber = "+4670123458",
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 4,
                            Email = "james.brown@thedot.com",
                            FirstName = "James",
                            LastName = "Brown",
                            PasswordHash = "$2a$11$4BxFB2IcLGWKxgBnVfWCtOG7OfxZ1DjCrbpOk98b.SSct39Vlg6.K",
                            PhoneNumber = "+4670123459",
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 5,
                            Email = "alice.johnson@email.com",
                            FirstName = "Alice",
                            LastName = "Johnson",
                            PasswordHash = "$2a$11$2I7hyxNZOEYpbnS89PZDNucKd5C5HZparOjN41Dt0/6LB1G/BkMZO",
                            PhoneNumber = "+4670123460",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 6,
                            Email = "bob.williams@email.com",
                            FirstName = "Bob",
                            LastName = "Williams",
                            PasswordHash = "$2a$11$2I7hyxNZOEYpbnS89PZDNucKd5C5HZparOjN41Dt0/6LB1G/BkMZO",
                            PhoneNumber = "+4670123461",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 7,
                            Email = "charlie.miller@email.com",
                            FirstName = "Charlie",
                            LastName = "Miller",
                            PasswordHash = "$2a$11$2I7hyxNZOEYpbnS89PZDNucKd5C5HZparOjN41Dt0/6LB1G/BkMZO",
                            PhoneNumber = "+4670123462",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 8,
                            Email = "diana.davis@email.com",
                            FirstName = "Diana",
                            LastName = "Davis",
                            PasswordHash = "$2a$11$2I7hyxNZOEYpbnS89PZDNucKd5C5HZparOjN41Dt0/6LB1G/BkMZO",
                            PhoneNumber = "+4670123463",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 9,
                            Email = "ethan.wilson@email.com",
                            FirstName = "Ethan",
                            LastName = "Wilson",
                            PasswordHash = "$2a$11$2I7hyxNZOEYpbnS89PZDNucKd5C5HZparOjN41Dt0/6LB1G/BkMZO",
                            PhoneNumber = "+4670123464",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 10,
                            Email = "fiona.taylor@email.com",
                            FirstName = "Fiona",
                            LastName = "Taylor",
                            PasswordHash = "$2a$11$2I7hyxNZOEYpbnS89PZDNucKd5C5HZparOjN41Dt0/6LB1G/BkMZO",
                            PhoneNumber = "+4670123465",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 11,
                            Email = "george.moore@email.com",
                            FirstName = "George",
                            LastName = "Moore",
                            PasswordHash = "$2a$11$2I7hyxNZOEYpbnS89PZDNucKd5C5HZparOjN41Dt0/6LB1G/BkMZO",
                            PhoneNumber = "+4670123466",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 12,
                            Email = "hannah.anderson@email.com",
                            FirstName = "Hannah",
                            LastName = "Anderson",
                            PasswordHash = "$2a$11$2I7hyxNZOEYpbnS89PZDNucKd5C5HZparOjN41Dt0/6LB1G/BkMZO",
                            PhoneNumber = "+4670123467",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 13,
                            Email = "ian.thomas@email.com",
                            FirstName = "Ian",
                            LastName = "Thomas",
                            PasswordHash = "$2a$11$2I7hyxNZOEYpbnS89PZDNucKd5C5HZparOjN41Dt0/6LB1G/BkMZO",
                            PhoneNumber = "+4670123468",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 14,
                            Email = "julia.jackson@email.com",
                            FirstName = "Julia",
                            LastName = "Jackson",
                            PasswordHash = "$2a$11$2I7hyxNZOEYpbnS89PZDNucKd5C5HZparOjN41Dt0/6LB1G/BkMZO",
                            PhoneNumber = "+4670123469",
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("RestaurantManagementSystem.Models.Booking", b =>
                {
                    b.HasOne("RestaurantManagementSystem.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RestaurantManagementSystem.Models.BookingTable", b =>
                {
                    b.HasOne("RestaurantManagementSystem.Models.Booking", "Booking")
                        .WithMany("BookingTables")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantManagementSystem.Models.Table", "Table")
                        .WithMany("BookingTables")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("RestaurantManagementSystem.Models.Dish", b =>
                {
                    b.HasOne("RestaurantManagementSystem.Models.Menu", "Menu")
                        .WithMany("Dishes")
                        .HasForeignKey("MenuId");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("RestaurantManagementSystem.Models.User", b =>
                {
                    b.HasOne("RestaurantManagementSystem.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RestaurantManagementSystem.Models.Booking", b =>
                {
                    b.Navigation("BookingTables");
                });

            modelBuilder.Entity("RestaurantManagementSystem.Models.Menu", b =>
                {
                    b.Navigation("Dishes");
                });

            modelBuilder.Entity("RestaurantManagementSystem.Models.Table", b =>
                {
                    b.Navigation("BookingTables");
                });
#pragma warning restore 612, 618
        }
    }
}
